#ifndef JONSON_CONFIG_H
#define JONSON_CONFIG_H

#define JSON_OBJECT_INITIAL_LOAD_FACTOR 0.75f
#define JSON_OBJECT_INITIAL_CAPACITY 16
#define JSON_ARRAY_INITIAL_CAPACITY 16

#endif /* JONSON_CONFIG_H */
